version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install OpenSSL
          command: |
            sudo apt update
            sudo apt install build-essential checkinstall zlib1g-dev -y

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
            - /home/ubuntu/nvm/versions/node/<version>/lib/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Unit Tests
          command: npm run test
      - run:
          name: Code Coverage Tests
          command: npm run test:coverage
      - run:
          name: Report Coverage Results
          command: npm run test:coverage:report
      - run:
          name: Code Lint Tests
          command: npm run test:lint
